name = "birthday-notify"
main = "dist/index.js"
compatibility_date = "2022-08-28"

[triggers]
crons = ["1 * * * *"]

[build]
command = "yarn build"

kv_namespaces = [
  # replace with the KV you created
  { binding = "BIRTHDAY_SUBSCRIPTIONS", id = "00000000000000000000000000000000" },
]

[vars]
# The notification title
NOTIFICATION_TITLE = "Today is somebody's Birthday!"

# Run the command below in your browser to generate one
# await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']).then(({ privateKey }) => crypto.subtle.exportKey('jwk', privateKey)).then((jwk) => JSON.stringify(jwk))
SERVER_JWK = "{\"alg\":\"ES256\",\"crv\":\"P-256\",\"d\":\"kij2rSkdm1TPKZl589si6xtNp1Ha3D3CK-HyqJEr5X0\",\"ext\":true,\"key_ops\":[\"sign\"],\"kty\":\"EC\",\"x\":\"3Hk_NF_Rn496C6pNsrV8YtGElOSn5QYWkapdGiTx2sE\",\"y\":\"8Z0_KqK0YL2_DlIM3jECoI-acla0aDcDQaeFkPd0ZQE\"}"

# The sub value needs to be either a URL or a mailto email address. This is so that if a push service needed to reach out to sender, it can find contact information from the JWT.
SERVER_JWT_SUB = "mailto:99479536+Aynh@users.noreply.github.com"
