on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          curl --silent \
            --request POST \
            "${{ vars.APP_SITE }}/api/trigger" \
            --header "x-trigger-key: ${{ secrets.APP_TRIGGER_KEY }}"
